
server:
  port: 8080

swapi:
  baseUrl: https://swapi.info/api/

database:
  username: rebels_rescue
  url: jdbc:mysql://localhost:3306/rebels_rescue?allowMultiQueries=true
  driver: com.mysql.cj.jdbc.Driver
  dialect: MYSQL